name: Soongpal Java CI with Gradle

on:
  push:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4

    - name: Ensure Gradle Wrapper is executable
      run: chmod +x ./gradlew

    - name: Build Spring Boot JAR
      run: |
        ./gradlew clean bootJar -x test
        ls -l build/libs/

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: soongpal-artifact
        path: build/libs/*.jar

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
    - name: Download build artifact
      uses: actions/download-artifact@v4
      with:
        name: soongpal-artifact

    - name: Remove unnecessary plain JARs
      run: rm -f *-plain.jar

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
        aws-region: ap-northeast-2

    - name: Upload JAR to S3
      run: |
        set -e
        echo "Current directory: $(pwd)"
        ls -R   # 디렉토리 구조 출력
        JAR_FILE=$(find $GITHUB_WORKSPACE -name "*.jar")
        echo "Found jar: $JAR_FILE"
        aws s3 cp "$JAR_FILE" s3://${{ secrets.S3_BUCKET_NAME }}/soongpal-latest.jar

    - name: Deploy to EC2 via SSM
      run: |
        aws ssm send-command \
        --instance-ids ${{ secrets.EC2_INSTANCE_ID }} \
        --document-name "AWS-RunShellScript" \
        --parameters 'commands=[
          "#!/bin/bash",
          "set -e",
          "mkdir -p /home/ubuntu/firebase",
          "echo ${{ secrets.APPLICATION_YAML }} | base64 --decode > /home/ubuntu/application.yaml",
          "echo ${{ secrets.FIREBASE_KEY_JSON }} | base64 --decode > /home/ubuntu/firebase/soongpal-firebase-adminsdk.json",
          "aws s3 cp s3://${{ secrets.S3_BUCKET_NAME }}/soongpal-latest.jar /home/ubuntu/soongpal-0.0.1-SNAPSHOT.jar",
          "chown -R ubuntu:ubuntu /home/ubuntu/soongpal-0.0.1-SNAPSHOT.jar /home/ubuntu/application.yaml /home/ubuntu/firebase",
          "sudo systemctl restart soongpal"
        ]' \
        --query "Command.CommandId" --output text
